<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc92a489012a5a50e968e57bf683794d4
{
    public static $prefixLengthsPsr4 = array (
        'A' => 
        array (
            'Anais\\Evenement\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Anais\\Evenement\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc92a489012a5a50e968e57bf683794d4::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc92a489012a5a50e968e57bf683794d4::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitc92a489012a5a50e968e57bf683794d4::$classMap;

        }, null, ClassLoader::class);
    }
}
